Proxy_filename          = x509up
Proxy_path              = /afs/cern.ch/user/l/lfavilla/private/$(Proxy_filename)
universe                = vanilla
x509userproxy           = $(Proxy_path)
use_x509userproxy       = true
transfer_input_files    = $(Proxy_path)
+JobFlavour             = "tomorrow"
executable              = /afs/cern.ch/user/l/lfavilla/RPC/analyzer/condor/9606_380466_withNoisyStripsCleaning/Barrel_2/runner.sh
arguments               = 
output                  = /afs/cern.ch/user/l/lfavilla/RPC/analyzer/condor/9606_380466_withNoisyStripsCleaning/condor/output/analyzer_9606_380466_Barrel_2.out
error                   = /afs/cern.ch/user/l/lfavilla/RPC/analyzer/condor/9606_380466_withNoisyStripsCleaning/condor/error/analyzer_9606_380466_Barrel_2.err
log                     = /afs/cern.ch/user/l/lfavilla/RPC/analyzer/condor/9606_380466_withNoisyStripsCleaning/condor/log/analyzer_9606_380466_Barrel_2.log
queue
