Proxy_filename          = x509up
Proxy_path              = /afs/cern.ch/user/l/lfavilla/private/$(Proxy_filename)
universe                = vanilla
x509userproxy           = $(Proxy_path)
use_x509userproxy       = true
transfer_input_files    = $(Proxy_path)
+JobFlavour             = "tomorrow"
executable              = /afs/cern.ch/user/l/lfavilla/RPC/analyzer/condor/9606_380470_noNoisyStripsCleaning/Endcap_7/runner.sh
arguments               = 
output                  = /afs/cern.ch/user/l/lfavilla/RPC/analyzer/condor/9606_380470_noNoisyStripsCleaning/condor/output/analyzer_9606_380470_Endcap_7.out
error                   = /afs/cern.ch/user/l/lfavilla/RPC/analyzer/condor/9606_380470_noNoisyStripsCleaning/condor/error/analyzer_9606_380470_Endcap_7.err
log                     = /afs/cern.ch/user/l/lfavilla/RPC/analyzer/condor/9606_380470_noNoisyStripsCleaning/condor/log/analyzer_9606_380470_Endcap_7.log
queue
